name: Update Google Reviews Count

on:
  schedule:
    - cron: '0 6 * * *' # daily 06:00 UTC 
  workflow_dispatch: {} # start manual via "Run workflow"-Button

permissions:
  contents: write

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: check repository 
        uses: actions/checkout@v4

      - name: set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependecies 
        run: npm install

      - name: check for reviews 
        run: npm run scrape

      - name: commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reviews.json
          git diff --staged --quiet || git commit -m "chore: reviews.json aktualisiert [skip ci]"
          git push

      - name: empty jsDelivr-Cache 
        if: success()
        run: |
          curl -s "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/reviews.json" || true
